export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const MARK_COMPLEETD = "MARK_COMPLEETD";
export const MARK_INCOMPLETE = "MARK_INCOMPLETE";
export const FILTER_TODOS = "FILTER_TODOS";
export const MARK_ALL_COMPLETED = "MARK_ALL_COMPLETED";
export const UPDATE_SERACH_TERM = "UPDATE_SERACH_TERM";

